version: '3'

services:
  app:
    image: cacadosman/infinite-overflow
    restart: always
    tty: true
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=cacadosman.com,www.cacadosman.com
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=cacadosman.com,www.cacadosman.com
    networks:
      - nginx-proxy

#Docker Networks
networks:
  nginx-proxy:
    external: true