version: '3'

services:
  app:
    image: cacadosman/infinite-overflow
    restart: always
    tty: true
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=cacadosman.com,www.cacadosman.com
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=cacadosman.com,www.cacadosman.com
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge